# Generated by Django 2.2.6 on 2019-10-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=50)),
                ('logo_url', models.TextField(blank=True)),
                ('manager_name', models.CharField(blank=True, max_length=200)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('manager_guid', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
