# Generated by Django 2.2.6 on 2019-10-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YahooTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=50)),
                ('logo_url', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Yahoo Team',
                'verbose_name_plural': 'Yahoo Teams',
            },
        ),
        migrations.CreateModel(
            name='YahooGUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('yahoo_guid', models.CharField(max_length=150)),
                ('manager_name', models.CharField(max_length=150)),
                ('yahoo_team', models.ManyToManyField(related_name='guid_teams', to='JJE_Main.YahooTeam')),
            ],
            options={
                'verbose_name': 'Yahoo GUID',
                'verbose_name_plural': 'Yahoo GUIDs',
            },
        ),
    ]
