# Generated by Django 2.2.6 on 2019-10-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JJE_Waivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverclaim',
            name='claim_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
